# Generated by Django 5.2 on 2025-04-15 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetApp', '0003_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
    ]
