# Generated by Django 5.2 on 2025-04-16 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetApp', '0004_remove_contactmessage_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
