# Generated by Django 5.2 on 2025-04-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetApp', '0005_contactmessage_sent_at_contactmessage_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
